### ISSUE TITLE
Deployed Storybook should represent latest release

### ISSUE THREAD

**Issue by dferber90** [commercetools/ui-kit#104]
The Storybook available at https://uikit.commercetools.com/ should represent the version available in the latest release, instead of the latest development stage to avoid confusion and bugs.

This was not possible the last time we checked with Netlify. We might need to change our deployment setup for this.

Once we fixed this, a related idea is to have a second deployment with a dedicated URL which shows the latest stage of UI-Kit, e.g. https://uikit-latest.commercetools.com/ or https://latest.uikit.commercetools.com/.

**Comment by emmenko** [comment]
I think it would be cool to have the documentation site supporting multiple releases with a version switcher. So that the default points to `latest`, you can also inspect `next` versions (and old versions as well of course).

A lot of libraries to that.

We could try to use https://docusaurus.io/ as they supporting [versioning](https://docusaurus.io/docs/en/versioning), translations and search out of the box.
I also like the "Live JSX Editor" parts (e.g. in the https://reactjs.org/ website) to interact/play with the components (it's powered by https://github.com/FormidableLabs/react-live).

Just an idea, we can think about it 😇

**Comment by dferber90** [comment]
I would not want to mix the concern of having storybook represent the latest release with the addition of a documentation website.

PS: I've heard good things about https://www.docz.site/ as well, but let's not discuss this here.

**Comment by emmenko** [comment]
> I would not want to mix the concern of having storybook represent the latest release with the addition of a documentation website.

The point is that storybook won't be used anymore for the production website. Therefore I believe those are related concerns. We can discuss this in a different issue though, if you prefer.

> I've heard good things about https://www.docz.site/

Yes that's only good but it does not have features like versioning, etc.

**Comment by dferber90** [comment]
A documentation website is a bigger effort and it would be nice to have this problem solved in the meantime. Right now our components are still changing a lot and it would be a wasted effort to write beautiful documentation for components which will change/get removed soon.

For example we need to reorganize buttons&links, figure out which `size` props to use and we need to figure out the design tokens, add a grid system.

After that is the earliest I'd start thinking about a documentation site to avoid wasting efforts. So even if the storybook gets replaced by a doc website at some point (which we haven't decided on), I'd still like to fix this problem in the meantime.

**Comment by tdeekens** [comment]
I would love a good documentation site but I think given that we only use UIKit internally so far I would like to focus on components in the mean time. Given we have more custom apps out there and more people actually using it we can iterate on the documentation site and maybe even involve them in deciding what would help. Right now it just feels like we would all feel good about a nicer documentation site or trying another tool. Not much more.

**Comment by emmenko** [comment]
> given that we only use UIKit internally so far I would like to focus on components

That's a wrong assumption, there are already people using it for customer projects (e.g. us team) and there will be more coming.

Also to be clear, since I have the feeling that my suggestion came out wrong: I'm not saying "drop everything and build a super duper website", I was merely proposing to solve this issue once we will start building the website (_unknown date_) so we can kill two birds with one stone.

---

Regarding the initial issue, I would like to avoid changing our deployment setup if possible. I also don't have a good solution in mind for achieving that and I'm not sure if it's worth the time working on this (if this is also likely to change in the future).

**Comment by tdeekens** [comment]
> customer projects (e.g. us team) 

Cool. Do we have a list of clients using it? US team is a user but not a client to me. Can we get/ask for feedback from them what they see missing in the docs?
