### ISSUE TITLE
Body.Text tone to warning value (PropType warning)

### ISSUE THREAD

**Issue by FlopiVG** [commercetools/ui-kit#1258]
**Describe the bug**
Actually you can set the property tone of Body.Text component to warning and set the color text in orange, but the component doesn't have that value as propType in tone props.

Is missing? or Body.Text tone can't be warning?

**To Reproduce**
Create a Body.Text component with tone prop `warning` and see console warning.

**Expected behavior**
Doesn't have to appear that propType validation warning

**Screenshots**
![image](https://user-images.githubusercontent.com/9992637/73943910-f13f5800-48f1-11ea-8690-6d0117564b7b.png)

**Comment by jonnybel** [comment]
Hi. This is a reasonable question 😄 
I believe it was a design decision to not allow the `Text.Body` to have the `warning` tone, because usually for warnings we use the `Text.Detail`.

However, I don't see any harm in allowing it (or any other tones for all the Text components), and I think this may be reconsidered, so I will raise this question with our Design team.

**Comment by mariabarrena** [comment]
Hi @FlopiVG 
Yes, @jonnybel is right. It was a design decision. The `warning` tone should only be used in texts in two different cases:

- In inputs, for both the text within the input and in the warning message below those (where we use `Text.Detail`). 
- In the “view access only” label indication

A `Text.Body` should never be displayed with that tone prop if it is not covered in those two cases. If you want to warn users about something, you should use the `WarningIcon` with the `warning` tone instead. However the text next to it should always be in `solid` tone.

**Comment by FlopiVG** [comment]
@mariabarrena @jonnybel ok, thanks for the clarification :)
