### ISSUE TITLE
Prop passing for the AsyncSelectInput

### ISSUE THREAD

**Issue by parthikrb** [commercetools/ui-kit#2047]
### Request Overview
In Products, we have a [scenario](https://jira.commercetools.com/browse/PCM-2506) where we want to keep the select options OPEN even after selecting an option (for better UX).
On investigating the existing AsyncSelectInput component, we noticed that `AsyncSelect` from `react-select` is abstracted behind the implementation

We also noticed that the [react-select](https://react-select.com/props) library provides a prop called `closeMenuOnSelect` to keep the options open, but unfortunately UI-kit component is not exposing the prop.

So, as part of this request, we want to implement the prop passing for `closeMenuOnSelect`.

**Comment by mmaltsev-ct** [comment]
Hi @parthikrb, thanks for the request. Also, thank you for the suggested solution. Is it still relevant or did you find a workaround at the moment?

It sounds like a good first contribution topic. Do you think you'll be comfortable creating a PR for this feature request? Otherwise, our team can help with implementing this feature.

On the other note, if we are planning to expose the `closeMenuSelect` property anyway, let's do it for all _react-select_-based components (`AsyncCreatableSelectInput`, `AsyncSelectInput`, `CreatableSelectInput`, `SearchSelectInput`, `SelectInput`).

**Comment by parthikrb** [comment]
@mmaltsev-ct, It is still relevant to our feature request as there is no workaround to keep the menu open.

For the second question, yes, I would like to contribute to this and will create a PR soon.

Thanks.
