### ISSUE TITLE
Submit inputs with 'Enter'

### ISSUE THREAD

**Issue by antoniolodias** [commercetools/ui-kit#2184]
**Describe the solution you'd like**
I would like to have the option to submit whichever input with 'Enter' out of the box. My current issue is with [NumberInput](https://uikit.commercetools.com/?path=/story/components-inputs--numberinput), but I think all inputs would benefit from it, [DateInput](https://uikit.commercetools.com/?path=/story/components-inputs--dateinput) would be another example

**Describe alternatives you've considered**
Surround the component in question with a `div` that listens to the event works, but it would be amazing if we didn't have to add the `div`

`<div onKeyDown={({ key }) => key === 'Enter' && handleSubmit()}>
                <Component />
              </div>`

@tdeekens also suggested a hook like [react-use-keypress](https://github.com/jacobbuck/react-use-keypress#readme)

**Additional context**
I am currently working on order search sidebar where we have a lot of inputs that can be submitted separately, pressing 'Enter' would be helpful. I can imagine that maybe in some cases it can also be annoying, so maybe this should be triggered with a prop and not by default, or being by default but leaving the option to opt out

**Comment by CarlosCortizasCT** [comment]
Hi @antoniolodias 

Thanks for sharing this problem, however I'm not sure we should be changing `ui-kit` inputs components because of this as browsers already support submission for forms when clicking _Enter_. I mean, if you have `form` with some input fields and a `submit` input/button, it should be submitted automatically when using the _Enter_ key (also if there is only one input field in the form).
I found [this article](https://www.tjvantoll.com/2013/01/01/enter-should-submit-forms-stop-messing-with-that/) very helpful regarding this functionality.

Perhaps you have any other use case when you need to use input fields outside a form?

**Comment by antoniolodias** [comment]
@CarlosCortizasCT Thank you very much, I will try that out and let you know if we should close this issue

**Comment by antoniolodias** [comment]
Suggested change fixed the issue with the combination of adding `type="submit"` to the submit button.
Thanks @CarlosCortizasCT
