### ISSUE TITLE
DateInput shows wrong format with locale en-GB on custom application

### ISSUE THREAD

**Issue by robin-ta** [commercetools/ui-kit#2301]
**Describe the bug**
The format for DateInput is showing “MM/DD/YYYY” on our custom application both locally and on the published versions. I want it to show “DD/MM/YYYY” (with an English locale, I have tried with en-GB)

I read the document that the format should show depending on the user’s locale. The locale is switching the format, but only for some of the languages. The problem we get is when the user’s locale is on “en-GB” it still shows “MM/DD/YYYY” in our custom application, while your application “Discounts” is showing correct throughout the test.

**To Reproduce**

1. Change profile language to "en-GB"
2. Add the DateInput to a custom application
3. Go to the custom application
4. Choose a date with makes it obvious which month it is (30 on October for example)
5. Get 10/30/2022

**Expected behavior**
Should show 30/10/2022

**Screenshots**
The en-US and de are showing correct but not en-GB
![image](https://user-images.githubusercontent.com/97515145/193550119-9ded75c4-ccd0-44b8-82ef-9d76f551543a.png)

**Comment by CarlosCortizasCT** [comment]
Hello @robin-ta 

We'll look into this issue and let you know as soon as we find an explanation.

**Comment by CarlosCortizasCT** [comment]
Hello @robin-ta 

So we found out the issue is not related to the `ui-kit` component itself but it has to do with some dependencies mismatches in the `app-kit`'s dependencies.

We've released a new `app-kit` version ([21.17.0](https://github.com/commercetools/merchant-center-application-kit/releases/tag/v21.17.0)) which addresses this problem so you should update the dependencies in your project.

Thanks.

**Comment by robin-ta** [comment]
Hello @CarlosCortizasCT,
It works good now, thanks for the help!
