### ISSUE TITLE
Invalid icons names

### ISSUE THREAD

**Issue by emmenko** [commercetools/ui-kit#259]
**Describe the bug**
After fixing the naming for the latest new icons (#251), I noticed that most of them have invalid naming.

**Current behavior**
There are some icons that are named after the context where they are being used in the MC.

**Expected behavior**
Icons should be named according to what the icons itself represents, not the context.

---

If we decide to rename them, we should document properly which icons got renamed to what, to make it simple to migrate.

See [proposal naming down below](https://github.com/commercetools/ui-kit/issues/259#issuecomment-441624081)

**Comment by emmenko** [comment]
I would suggest that we propose the changes and then we confirm the names with the design team.

So far I think we should rename:

|Invalid name|Correct name|
| --- | --- |
| AddressBillingIcon | |
| AddressShippingIcon | |
| ArrowGraphDownIcon | |
| ArrowGraphLeftIcon | |
| ArrowGraphRightIcon | |
| ArrowGraphUpIcon | |
| BoxProductIcon | |
| CategoryTreeIcon | |
| CustomSettingsIcon | |
| CustomViewIcon | |
| CustomerFilledIcon | |
| CustomerIcon | |
| ProjectSettingsIcon | |
| ReturnInfoIcon | |
| TagDiscountIcon | |

**Comment by tdeekens** [comment]
Renaming ArrowGraphLeftIcon to ArrowLeftIcon would create a conflict with the existing ArrowLeftIcon, right?

**Comment by emmenko** [comment]
> Renaming ArrowGraphLeftIcon to ArrowLeftIcon would create a conflict with the existing ArrowLeftIcon, right?

Yes I suppose so

**Comment by emmenko** [comment]
I updated the list with the icons and with a name proposal

**Comment by tdeekens** [comment]
Thanks. Random suggestions:

ReturnInfoIcon -> UndoIcon
CustomViewIcon -> UserCustomizedIcon
CustomSettingsIcon -> ??? not sure what the difference in meaning of CogIcon and this would be

**Comment by franzi-t** [comment]
Great! Other suggestions are:
ReturnInfoIcon -> BidirectionalArrowIcon
CustomSettingsIcon -> ApplicationCogIcon

**Comment by mariabarrena** [comment]
Do we have examples of how other companies are applying this so we can get ideas? I assume "expected behavior" means common practices on design systems that we should apply too. It would be goot to learn from those that are doing it right.

ManifestInvertedIcon: I would not use Manifest, as it has multiple interpretations (as a verb and as a noun) PaperDocInvertedIcon is more accurate of what it represents.

CogIcon: I would not use cog but rather cogwheel or gear as it is more appropriate of what that icon represents. A cog is just a tooth of the whole item. Then CustomSettingsIcon could be ScreenGearIcon and CustomViewIcon could be ScreenUserIcon.

TagStackedIcon would be more appropriate to use PriceTagStackedIcon as we use something on the UIkit called "tags" and can be misleading perharps.

I would not change just a group of icons but change all the names of all the icons at once, as some of them are related to other and the entire family should follow some consistency now we are going to have proper names.

**Comment by emmenko** [comment]
Sure thing, suggestions are very welcomed!

**Comment by coolmilo** [comment]
I agree that we need to use standard naming conventions. The language written should be clear and simple and easy to identify when searching for it or looking through the code.
Do we need to have "Icon" for all the icons name? If yes, we need to separate it from the actual name.
billIcon or bill-icon

Having all lower cases will help reduce making typing errors.
My suggestion below are based on standards as used in places like https://fontawesome.com/icons?d=gallery 

AddressBillingIcon |   | ico-paperbill
AddressShippingIcon |   | ico-truck
ArrowGraphDownIcon |   | ico-arrow-down
ArrowGraphLeftIcon |   | ico-arrow-left
ArrowGraphRightIcon |   | ico-arrow-right
ArrowGraphUpIcon |   | ico-arrow-up
ArrowLeftIcon |   | ico-chevron-left
ArrowRightIcon |   | ico-chevron-right
BoxIcon |   | ico-cube
BoxProductIcon |   | ico-box
CategoryTreeIcon |   | ico-tree-structure
CustomSettingsIcon |   | ico-page-settings
CustomViewIcon |   | ico-user-settings
CustomerFilledIcon |   | ico-user
CustomerIcon |   | ico-user-linear
ProjectSettingsIcon |   | ico-cog
ReturnInfoIcon |   | ico-exchange
TagDiscountIcon |   | ico-tag-multiple

**Comment by tdeekens** [comment]
> Do we need to have "Icon" for all the icons name

We do not need to refer to them as such but from a code perspective partly. UIKit has one main export (API) which makes the library resilient against changes and easier to use. Given that you need to import something from UIKit you refer to it's "nature" `SelectInput`, `LinkButton`, etc same for icons `ArrowRightIcon`. Otherwise it would get a bit confusing e.g. by importing only `ArrowRight` without knowing what it is. We could restructure everything to be prefixed so `Icons.ArrowRight` if that's better. However, for consistency we should also restructure all fields/inputs then to e.g. `Inputs.Text` a quite drastic and breaking change for any consumer of UIKit.

Anyway, we do not need to refer to them as `ArrowRightIcon` internally or even when showing them in our style guide by just referring to them as `ArrowRight`.

> Having all lower cases will help reduce making typing errors.

Fontawesome has a dasherized naming schema while we have a camel cased one. The third would be snake case.

1. Snake case: angle_right_icon
2. Camel case: AngleRighticon
3. Dasherized: angle-right-icon

Which one is picked should not matter too much I presume and all are interchangeable and can also be transformed by code. Also here we could display them daherized in our stylebook while in code they however have to be camel cased (syntax). Doing that seems a bit confusing as it introduces a mapping between things. Normally CSS libraries use a dasherized casing while component libaries go for a camel cased variation (like we do).

Hope that all makes at least decent sense.

**Comment by coolmilo** [comment]
Absolutely @tdeekens this gives a good overview!! I was not aware of the three name schemas 😳Thanks.
Personally, I like the separation for clarity, for example when working with them in Sketch.
I also reduced kept icon but reduced it to "ico" so that we know it's usage. Those are my suggestions and happy to hear from others but hope this does not blow up for @emmenko

**Comment by tdeekens** [comment]
> That's what we already do.

Cool. I guess we then rather wait to see if we can remove the Icon postfix without having a breaking change and then migrate all apps.
