### ISSUE TITLE
<CollapsiblePanel> header overlaps with <*SelectField> dropdown when the `isSticky` is passed as `true`

### ISSUE THREAD

**Issue by jaikumar-tj** [commercetools/ui-kit#2694]
**Describe the bug**
The dropdown option list of select fields seems to have z-index=1 which is same as the z-index of collapsible panels' header when the prop `isSticky` is passed as "true".

**To Reproduce**

1. Go to [Product detail page](https://mc.europe-west1.gcp.escemo.com/adnan-nodejs-test-project/products/858d0771-0d62-471f-9eeb-0a303875a32b/variants/1)
2. Click on any of the select field which are just above the collapsible panel
3. Notice the dropdown is going behind the header

**Expected behavior**
The dropdown should be visible on top of the header.

**Screenshots**
#### when `isSticky={true}`

<img width="852" alt="Screenshot 2024-01-19 at 13 51 17" src="https://github.com/commercetools/ui-kit/assets/83634106/d14ddebd-3603-41c2-956e-f5e0b021565a">

#### when `isSticky={false}`
<img width="867" alt="Screenshot 2024-01-19 at 13 51 29" src="https://github.com/commercetools/ui-kit/assets/83634106/287bb173-adae-4405-9287-013381a7eef1">

**Comment by CarlosCortizasCT** [comment]
Thanks for reporting @jaikumar-tj 

We'll take a look as soon as we can.

**Comment by CarlosCortizasCT** [comment]
Hi @jaikumar-tj 

So the collapsible panel header should have a positive `z-index` (`1`) when is sticky as it will be positioned on top of other elements.

The dropdown menu of the select input components also has a default `z-index` of `1` and that's why the collapsible panel wins in your case (as it comes later in the DOM).

However, [select inputs](https://uikit.commercetools.com/?path=/story/components-inputs-selectinputs--asynccreatableselectinput) expose a couple of props (`menuPortalTarget` and `menuPortalZIndex`) you can use to customize the `z-index` experience:
![image](https://github.com/commercetools/ui-kit/assets/97907068/67a0684a-d569-41ea-b32e-59e8a4c1af8e)

So something like this should work for you:
```jsx
<AsyncSelectField
  ...
 menuPortalZIndex={2}
 menuPortalTarget={document.body}
/>
```

Please let me know if this helps. 🙏

**Comment by jaikumar-tj** [comment]
Thanks @CarlosCortizasCT 
I'll try that. My use-case is that I will need to update custom fields which are also used in multiple places. Let me try out your solution and see if that has no consequence. 
If that fixes everywhere, then I'll update you and close this ticket.

**Comment by CarlosCortizasCT** [comment]
Hello @jaikumar-tj 

Could you please confirm if using the suggested solution was enough for your use case?

I'm asking just to know if we can close this issue.

**Comment by jaikumar-tj** [comment]
Hi @CarlosCortizasCT 

It is still under ux review and I'm waiting for any further comments from my team to see if this is fine or if they find any other issues. Once it gets done, I'll update you and close this ticket.

**Comment by jaikumar-tj** [comment]
My team is quite busy & couldn't review it yet the related PR is already deployed and we tackled the minor hiccup as well. We can close this ticket. Thanks @CarlosCortizasCT for your suggestion.

**Comment by jaikumar-tj** [comment]
There was one minor issue with this approach. The dropdown option is displayed like this (overlapping the headers) when user scrolls down. It looks a constant z-index cannot be used in such a case. We will leave it like this for now, incase if it is reported then we will get back to u.

<img width="1208" alt="Screenshot 2024-02-12 at 16 53 41" src="https://github.com/commercetools/ui-kit/assets/83634106/f90c1502-9879-4533-a00f-88543ccd6bd9">
