### ISSUE TITLE
Remove unsupported horizontalConstraints

### ISSUE THREAD

**Issue by dferber90** [commercetools/ui-kit#325]
Right now all of our components support all values of `horizontalConstraint` even if the constraint is too narrow for that particular component (e.g. in date inputs).

We want to go through all components and drop support of values for horizontalConstraint which don't make sense for that particular component (by dropping the values from the prop-types).

**Comment by montezume** [comment]
# Remove unsupported horizontalConstraints

#### FieldLabel

Drop `xs`

<details>
<summary>Show screenshots</summary>

**xs**
![screen shot 2019-01-14 at 10 24 36 am](https://user-images.githubusercontent.com/2425013/51104588-dbdb2580-17e6-11e9-9f57-6f199550012e.png)
</details>

## Fields

#### Select fields

This covers `AsyncCreatableSelectField`,`AsyncSelectField`,  `CreatableSelectField` and `SelectInput`

Drop `xs`

<details>
<summary>Show screenshots</summary>
**xs**

![screen shot 2019-01-14 at 10 28 05 am](https://user-images.githubusercontent.com/2425013/51104723-278dcf00-17e7-11e9-8c2e-3009fcde64db.png)

</details>

#### Date inputs and fields 

This covers `DateField`,`DateRangeField` and `DateTimeField`.

Drop `xs`, `s`

<details>
<summary>Show screenshots</summary>
**xs**

![screen shot 2019-01-14 at 10 37 56 am](https://user-images.githubusercontent.com/2425013/51105138-7c7e1500-17e8-11e9-9cbe-d6327e576601.png)

**s**
![screen shot 2019-01-14 at 10 38 01 am](https://user-images.githubusercontent.com/2425013/51105147-7f790580-17e8-11e9-8ed0-8a60e5cebca4.png)

</details>

#### Multiline text fields

This covers `LocalizedMultilineField` and `MultilineTextField`
* (for any "localized" input, we need to drop xs and s because the bottom "show all languages" overlaps passed the S width anyways...

Drop `xs` and `s`


<details>
<summary>Show screenshots</summary>

**xs**

![screen shot 2019-01-14 at 10 49 01 am](https://user-images.githubusercontent.com/2425013/51105711-0aa6cb00-17ea-11e9-9ca6-f4fc3eb106aa.png)


**s**

![screen shot 2019-01-14 at 10 48 56 am](https://user-images.githubusercontent.com/2425013/51105716-0e3a5200-17ea-11e9-804e-0862cff5b807.png)

</details>

#### LocalizedTextField
* (for any "localized" input, we need to drop xs and s because the bottom "show all languages" overlaps passed the S width anyways...
Drop `xs` and `s`

<details>
<summary>Show screenshots</summary>

**xs**

![screen shot 2019-01-14 at 10 53 05 am](https://user-images.githubusercontent.com/2425013/51105923-a9cbc280-17ea-11e9-9455-9c8284311bd5.png)


**s**

![screen shot 2019-01-14 at 10 53 09 am](https://user-images.githubusercontent.com/2425013/51105933-b05a3a00-17ea-11e9-9b4e-911a96b4cdd2.png)

</details>

#### MoneyField

Drop `xs` and `s`

<details>
<summary>Show screenshots</summary>

**xs**

![screen shot 2019-01-14 at 10 54 13 am](https://user-images.githubusercontent.com/2425013/51106018-e39cc900-17ea-11e9-8aee-f59ebdad6860.png)


**s**

![screen shot 2019-01-14 at 10 54 17 am](https://user-images.githubusercontent.com/2425013/51106041-f7e0c600-17ea-11e9-8d85-1efbcf78b305.png)

</details>

#### NumberField

Drop `xs`

<details>
<summary>Show screenshots</summary>

**xs**

![screen shot 2019-01-14 at 11 04 57 am](https://user-images.githubusercontent.com/2425013/51106510-4773c180-17ec-11e9-8dbd-189e846fe9e2.png)

</details>

#### TextFields
Covers `TextField` and `PasswordField`

Drop `xs` 

<details>
<summary>Show screenshots</summary>

**xs**

![screen shot 2019-01-14 at 11 04 08 am](https://user-images.githubusercontent.com/2425013/51106475-2b702000-17ec-11e9-9fa2-50a26e7d14d1.png)

</details>


#### TimeField

Drop `xs`

<details>
<summary>Show screenshots</summary>

**xs**

![screen shot 2019-01-14 at 11 05 51 am](https://user-images.githubusercontent.com/2425013/51106564-696d4400-17ec-11e9-931c-15678e7f4060.png)

</details>

## Inputs

#### Select inputs
Covers `AsyncCreatableSelectInput`, `AsyncSelectInput`, `SelectInput` and `CreatableSelectInput`

Drop `xs`

<details>
<summary>Show screenshots</summary>

**xs**

![screen shot 2019-01-14 at 11 07 57 am](https://user-images.githubusercontent.com/2425013/51106648-aafdef00-17ec-11e9-9bea-a0d0cf5ff3f9.png)

</details>

#### Date Inputs
Covers `DateInput`, `DateRangeInput` and `DateTimeInput`

Drop `xs`, `s`

<details>
<summary>Show screenshots</summary>

**xs**

![screen shot 2019-01-14 at 11 15 43 am](https://user-images.githubusercontent.com/2425013/51106976-c61d2e80-17ed-11e9-802d-d8b2e09308a1.png)

**s**

![screen shot 2019-01-14 at 11 15 48 am](https://user-images.githubusercontent.com/2425013/51106984-cc130f80-17ed-11e9-9689-fa9bf4698ba8.png)

</details>

#### LocalizedMoneyInput

Drop `xs`, `s`

<details>
<summary>Show screenshots</summary>

**xs**

![screen shot 2019-01-14 at 11 16 39 am](https://user-images.githubusercontent.com/2425013/51107028-f2d14600-17ed-11e9-85c8-1f58f4269112.png)

**s**

![screen shot 2019-01-14 at 11 16 42 am](https://user-images.githubusercontent.com/2425013/51107045-f795fa00-17ed-11e9-8a44-c671bd32da05.png)

</details>

#### Multiline text inputs

This covers `LocalizedMultilineInput` and `MultilineTextInput`

Drop `xs`, `s`

<details>
<summary>Show screenshots</summary>

**xs**

![screen shot 2019-01-14 at 11 20 03 am](https://user-images.githubusercontent.com/2425013/51107204-62473580-17ee-11e9-9447-1aacc8efaca6.png)

**s**

![screen shot 2019-01-14 at 11 20 08 am](https://user-images.githubusercontent.com/2425013/51107210-66735300-17ee-11e9-85a3-496c594c71ab.png)

</details>

#### Text Inputs
Covers `TextInput` and `PasswordInput`

Drop `xs` 

<details>
<summary>Show screenshots</summary>

**xs**

![screen shot 2019-01-14 at 11 22 50 am](https://user-images.githubusercontent.com/2425013/51107313-bfdb8200-17ee-11e9-9eb5-89f06fc2581d.png)

</details>

#### TimeInput

Drop `xs`

<details>
<summary>Show screenshots</summary>

**xs**

![screen shot 2019-01-14 at 11 23 16 am](https://user-images.githubusercontent.com/2425013/51107365-e8637c00-17ee-11e9-982a-e0d89bf39dbe.png)

</details>
