### ISSUE TITLE
SSR - flash of unstyled content

### ISSUE THREAD

**Issue by montezume** [commercetools/ui-kit#353]
A user reported that when using UI-Kit with a site generator such as Gatsby or Nextjs, they would experience a flash of unstyled content. We should look into this and provide a fix if possible.

**Comment by dferber90** [comment]
Not sure about the specifics of Gatsby. I can explain the problem with server-side rendering in general.

The flash-of-unstyled-content happens because we use CSS-in-JS instead of supplying global styles. The JS-bundle needs to be downloaded, parsed & executed before the styles get applied, as it contains the styles. However when using server-side rendering the markup is already provided by the server (but the CSS isn't injected into the head). That's why the flash-of-unstyled-content happens.

If we weren't rendering on the server, then there would be no markup and the styles and markup would get applied at the same time - and no flash-of-unstyled-content would happen. However that's bad because it delays the time until the content is visible.

The solution would be to allow the server-side render to collect the used stylesheets while rendering and let it inject these styles into the response. Then the styles arrive on the browse with the initial markup and the flash-of-unstyled-content is avoided.

To make this work, the consumers of ui-kit would need to extract the used CSS, collect it while rendering and inline it into the response. 

[`styled-comonents`](https://www.styled-components.com/docs/advanced#server-side-rendering) explains how to do this in their docs for example and I have it working in [lovely-webapp](https://github.com/dferber90/lovely-webapp).

**Comment by emmenko** [comment]
I had a chat with @montezume about this and I suggested that we could replace our CSS modules with components styled with e.g. `emotion` (since we're already using it).

Then we can simply use the SSR utils from the library without any additional effort.

At the end, for consumers of ui-kit, it does not matter at all which styling library we use.

**Comment by emmenko** [comment]
Btw, I've played around a bit with Gatsby and MDX and I found out that you can map your own "design system" components to the markdown elements! 🤩

https://gatsby-mdx.netlify.com/guides/using-design-system-components

That's pretty dope!! 🙌

<img width="1440" alt="screenshot 2018-12-23 at 12 07 42" src="https://user-images.githubusercontent.com/1110551/50382984-6b3f5e00-06ab-11e9-8bba-4db48bff9ae0.png">

/cc @nkuehn

**Comment by nkuehn** [comment]
Yes, I saw the design system approach, too.  
I find it very interesting for more complex elements like images, tables, code blocks, having auto bookmarkable IDs on headings etc. pp.  All the little things we're currently doing with jQuery and fancy content-generating CSS at the moment.

**Comment by montezume** [comment]
I think the simplest solution would be to stop inlining our css into JS, and extract it into a separate CSS file.

**Comment by montezume** [comment]
Yeah, if we go all into a css-in-js library like `emotion`, then consumers can use either [gatsby-plugin-emotion](https://www.gatsbyjs.org/packages/gatsby-plugin-emotion/) and SSR *should* work out of the box.

**Comment by emmenko** [comment]
Yes that would also be my understanding as mentioned [here](https://github.com/commercetools/ui-kit/issues/353#issuecomment-449466455).

Maybe we should do some testing, just to be sure it works 😉

**Comment by montezume** [comment]
But it's a pretty opinionated approach. See this [discussion](https://github.com/JedWatson/react-select/issues/2706) for some blowback against users having to use something like emotion-server. This might not be as much of an issue with emotion 10 then.

**Comment by montezume** [comment]
![problemz](https://user-images.githubusercontent.com/2425013/51333581-57a2cf80-1a7e-11e9-9d00-6bc48b86f62e.gif)

**Comment by montezume** [comment]
Definitely recreatable 😆

**Comment by montezume** [comment]
So it looks like using `emotion` fixes the problem

![fix](https://user-images.githubusercontent.com/2425013/51334968-37c0db00-1a81-11e9-966d-cbc75bcccfcd.gif)

**Comment by montezume** [comment]
Now that we are using CSS in JS, we have solved this issue 🎉 💯

**Comment by kamanwu** [comment]
I use UI-Kit with Gatsby to create a site, and still have this FOUC issue.  I use react-helmet to include uikit css/js files in the head.  Did I do something wrong?
