### ISSUE TITLE
"Intro" page for storybook

### ISSUE THREAD

**Issue by emmenko** [commercetools/ui-kit#407]
I just noticed that when going to https://uikit.commercetools.com the "Forms Guide" is the first page that gets rendered.

I think this is a bit confusing for users that visit the website for the first time.

As long as we don't have a proper documentation website, we should at least have an intro page or something. Maybe we can put the repo readme for now.

**Comment by dferber90** [comment]
I also noticed this and would welcome it! I wouldn't use the README though.

<details>
<summary>Technical</summary>

In the beginning I was confused what the order on the left of storybook depends on. But it turns out that we only need to change the order here https://github.com/commercetools/ui-kit/blob/058e3f27e4e8b2375c724b7610ee5db81de15974/.storybook/config.js#L36-L41


So to make sure the readme gets rendered first, we'd need to import that as the first thing (and maybe avoid importing it again later on).

</details>

**Comment by emmenko** [comment]
Have you checked the PR that I opened? Isn’t that enough for now?

**Comment by dferber90** [comment]
That comment was written before your PR was opened.
