### ISSUE TITLE
Fix specificity problem of margin for Spacings -> Text components

### ISSUE THREAD

**Issue by emmenko** [commercetools/ui-kit#542]
The `margin: 0` set on the typography components is really annoying when using them with e.g. `<Spacings.{Inline,Stack}>` components, because the margin from the spacing components doesn't get applied (lower specificity).
To work around that, you would wrap the `<Text>` components in a `<div>`.

Should we maybe simply force the spacing components to apply their margin by using `!important`?
It feels like a little hack but maybe it's more of a trade-off.

Thoughts?

**Comment by tdeekens** [comment]
Even though I feel bad about the good old div soup I like the wrapping more than the specificity hack through CSS. 

Can you eloborate why the Spacing ends up with a lower specificity? I fail to understand why that happens and the spacing of it get overwritten.

**Comment by emmenko** [comment]
The `Spacings` component uses `> * + *` to set the margin on the direct children. However, the `Text` components set also `margin: 0`, which takes precedence over the `Spacings` selector:

<img width="1140" alt="image" src="https://user-images.githubusercontent.com/1110551/52900741-fe06ff80-31f9-11e9-9b9b-3d2ff8c57966.png">

With the `!important`, the `Spacings` margin is applied:

<img width="1133" alt="image" src="https://user-images.githubusercontent.com/1110551/52900744-1b3bce00-31fa-11e9-893b-ddc286b053fc.png">

**Comment by tdeekens** [comment]
Ah thanks. Get it now. Would it make maybe sense to, instead of leaking the problem into the text component by wrapping them in a div, have the spacing components map over their children? So the spacing would map and pack each child into a div applying a classname to add the spacing instead of doing it with the owl selector? Maybe that way we fix the problem for other cases than the text component too? It would only mean that children of spacinga would not be in the same flex context (given anybody expects that. I doubt it).

**Comment by emmenko** [comment]
Hmm I thought about it but that would only work if the children (whatever they are) accept a `className`, which most of them don't.
Other option is to map over the children and wrap them into a `<div>`, but I also don't like that because we're then kind of changing the markup and it just feels weird.

So that will leave us with the `!important` directive.

In general, we should try to avoid using it as much as possible, however I believe that in this particular case it actually makes sense. The reason is that `<Text>` components should rightfully have `margin: 0` as they should not dictate how the layout looks like. For that, we have things like spacing components. On the other hand, the `Spacings` components are also expected to _force_ their layout rules onto their children, so it's just totally confusing when that does not happen.

So I think we should just go with that instead of making consumers aware that they always have to workarounds the `<Text>` components by wrapping them into a `<div>`. We can also mention a _caveat_ in the `Spacings` components docs mentioning the usage of `!important`.

---

#### Alternative approach

We might want to rethink how our `<Text>` components are implemented. For instance, do they need to map to e.g. headline or paragraph elements or can they just be `<div>`s with some specific styling applied? Using `<div>`s, will prevent the need for `margin: 0`, which means that we don't need to use `!important` on the `Spacings` components.
From a semantic point of view, having ~~proper~~ correct HTML markup is usually a good thing, but maybe not necessarily for e.g. Merchant Center applications, as opposed to an actual content page website.

```jsx
// hypothetical API
<Text
  size="m"
  tone="primary"
  isBold={true}
  // ...
  /* htmlElement="h2" <-- optionally allow to render a specific HTML element, instead of a div */
>
  {'Hello'}
</Text>
```

**Comment by tdeekens** [comment]
Alright, I like this discussion but I think we start mixing a few things. Let me recap for me/us to get us to common ground.

### Options we saw

1. Wrapping each `Text` component in a `div`
2. Adding `!important` to the styling of `Spacings`
3. Somehow massage what we render into place

I think, from what I read, seem to agree that (correct me if I read that wrong):

1. Is not really optimal as it makes it only work for `Text` components and not others
2. We may feel bad for adding `!important` but it could be fine and worth a trade-off
3. You seem to dislike it but I fear we are not on the same page. You describe two things if I read you correctly:
     3.1 _only work if the children accept a `className`
     3.2 _changing what we render_

With 3. I was implying 3.2 to change what we render. You say "It feels weird and I don't like that so that leaves us with `!important`". To be frank: I find that a a bit of a short rigorous argument for the case (almost demotivating 😅). Anyway, without even arguing for us going with 3.2 I would actually state that it's a strength of React that you can actually do that. Many libraries to that incl. `react-router` and others. As long as it encapsulates things and eases an API I would hold little against it. Just my opinion though. That say, I wouldn't hold much against it.

That said I would be fine with `!important` (2.) in this case but still believe that 3.2 is not as bad is it was made. I don't fully understand your point about 3.1 and "would only work if children accept a `className`.

Then the "alternative approach". I agree that the MC might not have particular requirements to a11y but just stating "render divs for headers" might make us even end up with "divs for buttons". At least the same argument applies. It feels a too much of a "change" given we have a "margin:0"-problem. Anyway, from an a11y standpoint a `<button />` and `<div aria-role="button" />`, to my knowledge, share the same a11y characteristics. The same with an `<h3 />` and a `<div aria-role="h3 />`. Other libraries often allow consumers to specify as what things are rendered with an `as`-prop. So `<Text.Heading as="p">Hi<Text.Heading/>` renders a p instead of any h* element. I would not, and I think you meant also not to, default any `Text` component to render divs only by default (unless maybe we add aria-roles). For the MC it may not matter too much but I guess it would more for other consumers (e.g. docs website) which has a higher a11y bar. So I see options:

1. Not render "semantic markup" but apply decent aria-roles
2. Default to semantic markup but allow overwriting it
   - Not really sure it's the right cure to our problem at hand though

Long discussion, sorry. TL;DR in my head:

- Going with `!important` should be fine
- I disagree that altering markup with React is always a bad thing if it simplifies an API
    - In this case I would actually not dislike it (but it increases the div-soup)
- Allowing to specify what `Text` renders with something like `as`-prop is fine as long as defaults remain in tact as UIKit is not only for the MC
- Rendering always divs (going all in on div-soup) but aria-roles could be fine but I feel bad about it

### Appendix

This would be according to 3.2 an except of a `Spacings's render:

```jsx
{React.Children.map(this.props.children, child => 
  <div css={css`
    margin: ${getMargin(props.scale)} 0 0;
  `}>
    {child}
  </div>;
})}
```

**Comment by emmenko** [comment]
Thanks for the feedback so far! 🙏 I feel a bit bad now for starting different discussions. Let's maybe concentrate on the `margin` problem first.

> This would be according to 3.2 an excerpt of a `Spacings's render

Ah now I got what you meant 🤦‍♂️ I was somehow thinking that you wanted to `cloneElement` and passing a `className` to the child component.

> but I also don't like that because we're then kind of changing the markup and it just feels weird

Sorry for not being clear, I wasn't discouraging your proposal, I just meant that I don't like the fact that we change the markup.

---

As for the "alternative approach", we should probably discuss this separately. I just feel that we might need to rethink the API of the typography components a little. The `margin` is just one of the side-effects.

**Comment by jonnybel** [comment]
I heavily support the idea of having our uikit components support a `className` prop, because it would allow us not only overcome some certain specificity problems such as this one, but also generally improve the flexibility of all components, making their usage closer to using the native HTML elements.

It's a simple solution and we would avoid all the generally regarded as bad practices of using `!important`, altering markup and the excess of div wrappers.

**Comment by emmenko** [comment]
The purpose of a design system is for the components implementation to be as strict as possible in regards to the design rules, which means allowing components to be styled freely will defeat the purpose of a design system.
