### ISSUE TITLE
Better treeshaking support

### ISSUE THREAD

**Issue by emmenko** [commercetools/ui-kit#578]
I was reading some discussions about treeshaking in the react router repo and came across this point: https://github.com/ReactTraining/react-router/pull/6465

Apparently having `defaultProps` is bad for treeshaking. Or actually, static properties in general seem to be bad, both on classes and functions.

> Here's the problem. Babel transpiles static class properties outside of class iife which blocks uglify/terser from this iife.
> `defaultProps` will become a bad pattern soon since it's blocks treeshakability. For functions the problem is even more aggressive since it's not solvable these days.

We should maybe look into the following things:

- [ ] replace `defaultProps` with defaults in props destructuring
- [ ] remove `displayName`, as it should be inferred from the name of the class/function
- [ ] make sure that `propTypes` are properly stripped from the production build (I think we do that already)
- [ ] remove classes and use hooks (we might need to set a min peer dependency on react)

**Comment by tdeekens** [comment]
> static properties in general seem to be bad, both on classes and functions.

Those can be used for different purposes obviously (just to list a few):

1. `displayName` & `propTypes`
2. `isEmpty`, `createEmpty*` or any fn on inputs exposed that way
    - We can surely export them not as a static property but I also feel everybody kind of likes that pattern by now
3. Anything else not even react related

> remove classes and use hooks (we might need to set a min peer dependency on react)

Yes, we could do that maybe even now as we're using UIKit mainly withtin projects of the organization. 

Apart from the effort refactroing, how much value do we see in tree shaking generally? Is it just a nice dream we're trying to catch or do we already have numbers how much things are impacted badly by not having it? 

It generally feels a bit like a compiler/tooling issue by caused by how things are transpiled which forces us (maybe) to adapt. I just feel that not using classes and no static properties at all is a quite hard restriction. I somehow hope that by the fact, by taking this further, no React application being built with any classes, using any static properties right now is not ready to use tree-shaking is enough incentive for the community at large to solve the problem at the tooling layer (maybe).

**Comment by emmenko** [comment]
I feel that everyone is struggling a bit with this topic because there is no guidance on what to do and how to do it. This is also mostly a concern for library authors. I wish that there are rules and tooling on ensuring that your library is treeshackable.

The point of this issue is to look into some options that were mentioned in other repos that would help with making the code more treeshackable.
Whether we do that or not (refactoring) it's still debatable, we should first do some experimentation.

**Comment by emmenko** [comment]
I think this is not relevant anymore.
