### ISSUE TITLE
LinkButton should render the label in a <span> element

### ISSUE THREAD

**Issue by emmenko** [commercetools/ui-kit#588]
**Describe the bug**
The `<LinkButton>` renders the label in a `<Text.Body>` element, which defaults to `<p>`.
This becomes problematic when the `<LinkButton>` is rendered within a paragraph text, as nested `<p>` are not valid.

**To Reproduce**
<img width="1159" alt="image" src="https://user-images.githubusercontent.com/1110551/53809544-3c6c2080-3f55-11e9-9411-ffc57863e003.png">

https://codesandbox.io/s/k06ln8z2xr

**Expected behavior**
The `<LinkButton>` should render the label within a `<span>` element

**Comment by tdeekens** [comment]
Agreed. I would however also keep suggesting to have all `Text.*` components have an `as` prop which referes to the component used for rendering. It avoids us having to "break out" of being able to use the Text components in some cases only cause their wrapper is not "fitting". The `LinkButton` would just render `<Text.Body as="span">...</Text.Detail/>`.

**Comment by jonnybel** [comment]
I've opened a PR (#627) with a quick-fix for the `<p>` within a `<p>` problem.

However, there's still the problem with the `<div>` inside a `<p>` that I mentioned in the PR, which I want to address by changing the `Spacings.Inline` to render a `<span>` instead of a `<div>`, since the fundamental difference between the two is one being inline and the other not.

**Comment by tdeekens** [comment]
Having started a suggestion to add an `as` prop (in favour of `elementType`) I will re-open this issue.

It was raised that

>  would like to have an issue first where we discuss the usage and the API around this

So lets do that here? What are exact concerns of

1. Migrating from `elementType` to `as`?
2. Adding an restrictive (limited supported values) `as` prop to other components if needed?

**Comment by emmenko** [comment]
Some of the confusion was around the fact that `isInline` prop was not properly documented. Using that is the same as using the `as` prop, like mentioned above.

This leaves us to not necessarily need the `as` prop because we already have everything we need.
The point is: adopting the `as` prop doesn’t fix any problem per se, it would only be a renaming for, let’s say, “consistency and semantical” reasons.

So yeah, if we wish we can go ahead with that and go through the minimal hassle of migrating the props.
It’s not a high priority though and it doesn’t block anything afaik.

How do you guys wish to proceed here?

**Comment by tdeekens** [comment]
> This leaves us to not necessarily need the as prop because we already have everything we need.

Yes.

> The point is: adopting the as prop doesn’t fix any problem per se, it would only be a renaming for,

Nobody, after finding out about `isInline` said it would. We just all felt `as` is following a wider adopted pattern in the community. Plus it's just - really pick - less freaky to type than `elementType` which to me is just a strange name.

> It’s not a high priority though and it doesn’t block anything afaik.

No it wasn't. It was just a nicely sized task for @jonnybel which he implemented extremely nicely in his PR to me. Then sadly it exploded in opinions :).

> How do you guys wish to proceed here?

1. Given we make a breaking release due to other features: break it with it (changing it is just find and replace
2. Given we don't have a breaking release: do what @jonnybel tired to nicely with deprecation warnings
3. Not care about it

**Comment by emmenko** [comment]
Yes I agree.
Even though I might seem to play the devil's advocate here, I find the `as` prop also nicer to have.

I'm just asking those questions mainly to avoid us spending too much time dealing with migrations and to also take the chance to maybe evaluate how we can improve the API of the text components.

If we proceed with the "renaming", to keep things simple I would maybe prefer to do it like:
- add the `as` prop, without deprecating anything else
- in the next major we deprecate the other props (e.g. `elementType`, `isInline`, etc)
- in the next major we remove the deprecate props

I think this way we don't need anyone to "force" migrating the props when we introduce the `as` prop.

That's my point of view.

**Comment by tdeekens** [comment]
Sounds like a reasonable plan. Can you maybe say why we fear "I think this way we don't need anyone to "force" migrating the props when we introduce the as prop." so much by doing adding deprecation warnings straight away and removing in the next (one) major? I personally feel like we're almost the only user who cares to actually update in the MC. Meaning, no matter how "careful" we do this they will perceive the effect equally.

**Comment by emmenko** [comment]
I find it a good practice to consider an open source library (even if mainly used internally) to be treated as a library that is used by many people. Point being, we don't and shouldn't make assumptions about how people are going to use it and update it.

I also try to consider the point of view of users (developers), same as we would like to use and update any other library: it should be as easy and painless as possible to update.

So by doing it step-by-step, we can roll out the change more gracefully.

**Comment by jonnybel** [comment]
If we proceed with that 3-step deprecation process, I would suggest that we still provide some information about how `elementType` and `isInline` will be deprecated soon, because otherwise it's odd to have them along with `as` considering they do the same thing (and can't be used in conjunction).

The thrown warnings would help raise awareness in regards to it, and I personally don't find them too "alarming" since they're not actually errors, which is why I wouldn't mind having them right on step 1 (but which means we would have only have 2 steps).

Anyway, in regards to doing it in either 2 or 3 steps, I don't have a strong inclination to one way or another because this is merely semantics so there's no need to rush things.

**Comment by tdeekens** [comment]
> So by doing it step-by-step, we can roll out the change more gracefully.

I didn't argue for "break it - deal with it" I argued for

1. Add the prop and add a deprecation notice in the same next fix or minor release
2. Remove in next major release

Over how I understood you

1. Add the as prop as a minor release
2. Add deprecation warning in next major release
3. Remove elementType in another next major release

I am fully onboard with treating this as an prop Open Source library and you assuming I wouldn't confuses me cause I don't know where that thought comes from. I however, was only suggesting to keep the process to two steps instead of three.

**Comment by emmenko** [comment]
>  would suggest that we still provide some information about how elementType and isInline will be deprecated soon

Yes, that's usually documented in the release notes when the `as` prop will be introduced

> The thrown warnings would help raise awareness in regards to it, and I personally don't find them too "alarming" since they're not actually errors, which is why I wouldn't mind having them right on step 1 (but which means we would have only have 2 steps).

Our tests will fail because there are prop types warnings, so you have to fix them right away. That's also why I proposed to do it as a 3-steps process.

**Comment by tdeekens** [comment]
> Our tests will fail because there are prop types warnings

Which I actually like. Cause the refactor is easy and good and it will point us to the failing tests right away. That somebody else has failing tests (due to console.log throwing) in testing environments is not an assumption leading to having it a breaking change nor, to me at least, a good reason to offer a way essentially only to post-pone the solution.

**Comment by emmenko** [comment]
I think we said enough at this point. I'm fine with whatever you guys decide to do.
