### ISSUE TITLE
Table

### ISSUE THREAD

**Issue by dferber90** [commercetools/ui-kit#71]
We are seeing problems with our current table. We need to adapt the table.

The tables are next on our list and we are currently gaining all requirements. The topic will become clearer soon.

**Problems with Table**
- requires some cells to use tethering hack
- has unnecessary virtualization
    - prevents browser search from finding cells
    - we don't display enough rows to warrant having virtualization in the first place
- Does not update when inner components rerender (setState within them)
  - makes it hard to use table for forms or for dynamic stuff in tables (e.g. Collapsible Panel)

**Comment by dferber90** [comment]
I did some experimentation in #361.

**Comment by emmenko** [comment]
I suppose this will be one of the next big tasks. It might make sense to look more into it, together with the design team, in order to gather more specific requirements.

For instance, given our past experience, it might make sense to have different table implementations that are "optimised" for specific use cases as opposed to have one table that handles everything.

I think this might also be a good task for rotating a new contributor to the ui-kit.
